### ISSUE TITLE
What a fast integration!

### ISSUE THREAD

**Issue by vahidvdn** [EddyVerbruggen/nativescript-apple-sign-in#1]
Hi Eddy.

First of all, I should thank you for all of your work about NativeScript community. There are just a few days left about Apple new features in iOS13 beta, and you just supported one of the features. It's unbelievable. Also, I see you created more repos for those features. I appreciate it. I think it's the fastest growing framework between other cross-platform frameworks. 

Btw, going to close it, since it's not an issue with this plugin.

**Comment by EddyVerbruggen** [comment]
Hey Vahid! Thanks a  bunch for the compliments, much appreciated!
