### ISSUE TITLE
signInWithApple does not return any thing when building app with --env.uglify flag

### ISSUE THREAD

**Issue by lqt93** [EddyVerbruggen/nativescript-apple-sign-in#13]
### Please, provide the following version numbers that your issue occurs with:

- CLI: `6.4.1`
- Cross-platform modules: `6.5.1`
- Runtime(s):
` "tns-android": {
      "version": "6.4.1"
    },
    "tns-ios": {
      "version": "6.4.0"
    }
`
- Plugin(s): `"nativescript-apple-sign-in": "^1.1.0"`

### Please, tell us how to recreate the issue in as much detail as possible. 
I have implemented nativescript-apple-sign-in successfully when running in develop environment with `tns run ios`. It also worked as expected when I build it with `tns build ios`. However, when I build it with additional flag: `tns build ios --env.uglify`, signInWithApple function did not return anything, even catching error, after I entered AppleId's password successfully.

**Comment by sud80** [comment]
We are also facing similar issue where in the success or failure callbacks are randomly not getting invoked. The behaviour is such that the apple sign-in windows closes but the success / failure callback is not getting invoked. Happens in both scenarios when you successfully login or if you press cancel in the apple sign-in dialog. It is not consistent i.e. few times it succeeds and few times if fails. 

Again this behaviour is reproducible only in production build and not in simulator. 

CLI: 6.7.4
tns-ios: 6.5.2
nativescript-apple-sign-in version: 1.1.0
