### ISSUE TITLE
signInWithApple doesn't work on Simulator (iOS 13.6)

### ISSUE THREAD

**Issue by pattrawuth2530** [EddyVerbruggen/nativescript-apple-sign-in#14]
signInWithApple doesn't work on Simulator (iOS 13.6). 
It return an error "Auth failed with com.apple.AuthenticationServices.AuthorizationError error 1000"

I try: 
1. Simulator (iOS 13.5) >>> It 's works.
2. Real Device (iOS 13.6) >>> It 's works.
3. Simulator (iOS 13.6) >>> It 's doesn't work.

**Comment by EddyVerbruggen** [comment]
ok
