### ISSUE TITLE
Can't use nativescript-apple-sign-in On nativescript7

### ISSUE THREAD

**Issue by Philntps** [EddyVerbruggen/nativescript-apple-sign-in#16]
When import plugin and use it
I got ERROR : 

CONSOLE ERROR: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'collections' of undefined
TypeError: Cannot read property 'collections' of undefined

- CLI: 7.0.8
- "dependencies": {
    "@angular-devkit/build-angular": "^0.1000.3",
    "@angular/animations": "10.1.3",
    "@angular/common": "10.1.3",
    "@angular/compiler": "10.1.3",
    "@angular/core": "10.1.3",
    "@angular/forms": "10.1.3",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "10.1.3",
    "@angular/platform-browser-dynamic": "10.1.3",
    "@angular/router": "10.1.3",
    "@nativescript/angular": "^10.1.5",
    "@nativescript/background-http": "^5.0.0",
    "@nativescript/camera": "^5.0.0",
    "@nativescript/core": "7.0.0",
    "@nativescript/datetimepicker": "^2.0.2",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/imagepicker": "^1.0.0",
    "@nativescript/local-notifications": "^5.0.0",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/theme": "~2.2.1",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "audit": "0.0.6",
    "core-js": "^2.6.9",
    "fix": "0.0.6",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.20",
    "md5-typescript": "^1.0.5",
    "nativescript-android-utils": "^1.0.2",
    "nativescript-apple-sign-in": "^1.1.0",
    "nativescript-carousel": "^7.0.1",
    "nativescript-checkbox-ns-7": "^22.0.0",
    "nativescript-fabric": "^2.0.2",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-http-formdata": "^1.7.0",
    "nativescript-i18n": "^0.2.4",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-modal-datetimepicker": "^1.2.1",
    "nativescript-ns-apple-signin": "^1.0.4",
    "nativescript-phone": "^1.4.1",
    "nativescript-radiobutton": "^0.1.0",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-ui-sidedrawer": "^9.0.0-rc.3",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-windowed-modal": "^6.2.1",
    "nativescript-zxing": "^1.5.9",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.5",
    "scriptjs": "^2.5.9",
    "tslib": "1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.2",
    "@angular/cli": "10.1.3",
    "@angular/compiler-cli": "10.1.3",
    "@nativescript/ios": "7.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/types": "7.0.0",
    "@nativescript/webpack": "^3.0.0",
    "@ngtools/webpack": "^10.1.2",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.161",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "nativescript-dev-babel": "^0.2.1",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.0"
  }

**Comment by Nikkerlassen** [comment]
Does not seems to work on iOS 14 either. :(

**Comment by befirst** [comment]
the plugin is not updated to work with the last version of native script

someone need update dependencies in apple-sign-in.ios.js to
```
var platform_1 = require("@nativescript/core/platform");
var utils_1 = require("@nativescript/core/utils/utils");

and add something like this in package.json to
```"devDependencies": {
    "prompt": "^1.0.0",
    "rimraf": "^2.6.3",
    "semver": "^5.6.0",
    "@angular/common": "^10.1.0",
    "@angular/compiler": "^10.1.0",
    "@angular/compiler-cli": "^10.1.0",
    "@angular/core": "^10.1.0",
    "@nativescript/angular": "^10.1.5",
    "@nativescript/core": "~7.0.3",
    "@nativescript/types": "~7.0.3",
    "@nativescript/webpack": "~3.0.4",
    "tslint": "^5.12.1",
    "typescript": "~3.5.3"
  },

**Comment by befirst** [comment]
But I checked and haven't found jsArrayToNSArray in new utils

**Comment by befirst** [comment]
it should be `var utils_1 = require("@nativescript/core/utils/native-helper.ios");`

**Comment by befirst** [comment]
so the declaration of platform, utils and funcs I assume should look like
```
var platform_1 = require("@nativescript/core/platform");
var utils_1 = require("@nativescript/core/utils/native-helper.ios");
var jsArrayToNSArray = utils_1.collections.jsArrayToNSArray;
var nsArrayToJSArray = utils_1.collections.nsArrayToJSArray;
