### ISSUE TITLE
Only obtaining userId

### ISSUE THREAD

**Issue by cavalos0086** [EddyVerbruggen/nativescript-apple-sign-in#5]
### Make sure to check the demo app(s) for sample usage 
Checked!

### Make sure to check the existing issues in this repository 
Checked

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Signinwithapple only returns the userId not email, name or other credentials specified in the applesignIn documentation
### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
6.1.2

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
`"version": "6.1.2"`

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)

```
"tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
```

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-apple-sign-in": "^1.0.0",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.1.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.2.0",
    "typescript": "~3.5.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

1. Create a button to call appleSignIn
2. on Success, only the userid is retrieved.

### Is there any code involved? 
Yes:

home.component.html:
```
<GridLayout class="page">
    <!-- Add your page content here -->
    <FlexboxLayout flexDirection="row" alignContent="center" justifyContent="center">
        <Button text="signIn with applea" (tap)="onTap($event)"></Button>
    </FlexboxLayout>

</GridLayout
```

home.component.ts
```
async onTap(args: EventData) {
        console.log('tapped');
        if (isSignInWithAppleSupported()) {
            const signInResponse = await signInWithApple({
                // by default you don't get these details, but if you provide these scopes you will (and the user will get to choose which ones are allowed)
                scopes: ["EMAIL", "FULLNAME"]
            });
            this.user = signInResponse;
            console.dir(this.user);
        } else {
            console.log('SignInWithApple is not supported', '\n**********************');
        }
    }
```

and this is the output:
```
==== object dump start ====
user: #####.######.#####
==== object dump end ====
```

I also tried with a ts project (instead of angular) and the same behavior is happening. 

**Note:** I did read the part on your README where you said that for now only userID works but you also mentioned that it should be fixed in the upcoming beta. I assume that now the final release is out, it should work?

**Comment by cavalos0086** [comment]
Update!
I went into your source code  and I see that only user is getting passed in apple-sign-in.ios.js
```
ASAuthorizationControllerDelegateImpl.prototype.authorizationControllerDidCompleteWithAuthorization = function (controller, authorization) {
        console.log(">>> credential.state: " + authorization.credential.state);
        this.resolve({
            user: authorization.credential.user,
        });
    };
```

after modifying  it to:
```
ASAuthorizationControllerDelegateImpl.prototype.authorizationControllerDidCompleteWithAuthorization = function (controller, authorization) {
        console.log(">>> credential.state: " + authorization.credential.state);
        this.resolve({
            user: authorization.credential.user,
            email: authorization.credential.email,
            fullName: authorization.credential.fullName,
        });
    };
```
I am able to get those values :) 
I guess a better question is when would this be added officially?

**Comment by daweedm** [comment]
> Update!
> I went into your source code and I see that only user is getting passed in apple-sign-in.ios.js
> 
> ```
> ASAuthorizationControllerDelegateImpl.prototype.authorizationControllerDidCompleteWithAuthorization = function (controller, authorization) {
>         console.log(">>> credential.state: " + authorization.credential.state);
>         this.resolve({
>             user: authorization.credential.user,
>         });
>     };
> ```
> 
> after modifying it to:
> 
> ```
> ASAuthorizationControllerDelegateImpl.prototype.authorizationControllerDidCompleteWithAuthorization = function (controller, authorization) {
>         console.log(">>> credential.state: " + authorization.credential.state);
>         this.resolve({
>             user: authorization.credential.user,
>             email: authorization.credential.email,
>             fullName: authorization.credential.fullName,
>         });
>     };
> ```
> 
> I am able to get those values :)
> I guess a better question is when would this be added officially?

Since you can't rely on those values when sending to to your backend, you should better get the authorizationCode and identityToken, send them to your backend and then ask apple servers for the user data 


```js

ASAuthorizationControllerDelegateImpl.prototype.authorizationControllerDidCompleteWithAuthorization = function (controller, authorization) {
        console.log(">>> credential.state: " + authorization.credential.state);


        const authorizationCodeRaw = authorization.credential.authorizationCode;
        const identityTokenRaw = authorization.credential.identityToken;

        const authorizationCode = NSString.stringWithUTF8String(authorizationCodeRaw.bytes);
        const identityToken = NSString.stringWithUTF8String(identityTokenRaw.bytes);

        console.log(authorizationCode);
        console.log(identityToken);

        this.resolve({
            authorizationCode: authorizationCode.toString(),
            identityToken: identityToken.toString(),
            user: authorization.credential.user
        });
    };
```
